import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { internshipApi } from '../../api/client'

const TYPES = [['fdp', 'Faculty Development Program'], ['faculty_internship', 'Faculty Internship'], ['research_collaboration', 'Research Collaboration'], ['consultancy', 'Consultancy'], ['guest_lecture', 'Guest Lecture'], ['workshop', 'Workshop']]
export default function PostOpportunity() {
  const navigate = useNavigate(); const [form, setForm] = useState({ type: 'fdp', title: '', description: '', duration: '', stipend_or_honorarium: '', domain: '', eligibility: '', application_deadline: '' }); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const update = (key: string, value: string) => setForm(f => ({ ...f, [key]: value }))
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); setError(''); try { await internshipApi.createAcademicianOpportunity({ ...form, stipend_or_honorarium: form.stipend_or_honorarium ? Number(form.stipend_or_honorarium) : null, domain: form.domain.split(',').map(v => v.trim()).filter(Boolean) }); navigate('/company/internships') } catch (err: any) { setError(err?.response?.data?.detail || 'Failed to post opportunity.') } finally { setSaving(false) } }
  return <div className="max-w-3xl space-y-6"><div><h1 className="text-2xl font-bold text-gray-900">Post FDP / Opportunity</h1><p className="text-gray-500 mt-1">Share faculty development, research, teaching, and collaboration opportunities.</p></div><form onSubmit={submit} className="card space-y-5">
    <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Opportunity type *</label><select className="input" value={form.type} onChange={e => update('type', e.target.value)}>{TYPES.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Title *</label><input className="input" required value={form.title} onChange={e => update('title', e.target.value)} placeholder="e.g. AI in Education FDP" /></div></div>
    <div><label className="block text-sm font-medium text-gray-700 mb-1">Description</label><textarea className="input h-28 resize-none" value={form.description} onChange={e => update('description', e.target.value)} /></div>
    <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Duration</label><input className="input" value={form.duration} onChange={e => update('duration', e.target.value)} placeholder="5 days" /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Honorarium</label><input className="input" type="number" min="0" value={form.stipend_or_honorarium} onChange={e => update('stipend_or_honorarium', e.target.value)} /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Domains</label><input className="input" value={form.domain} onChange={e => update('domain', e.target.value)} placeholder="AI, education, cloud" /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Application deadline</label><input className="input" type="date" value={form.application_deadline} onChange={e => update('application_deadline', e.target.value)} /></div></div>
    <div><label className="block text-sm font-medium text-gray-700 mb-1">Eligibility</label><textarea className="input h-20 resize-none" value={form.eligibility} onChange={e => update('eligibility', e.target.value)} /></div>{error && <p className="text-sm text-red-600">{error}</p>}<div className="flex gap-3"><button type="submit" className="btn-primary" disabled={saving}>{saving ? 'Publishing...' : 'Publish opportunity'}</button><button type="button" className="btn-secondary" onClick={() => navigate(-1)}>Cancel</button></div>
  </form></div>
}
