import React from 'react'
import { organizationApi } from '../../api/client'
import { Building2, Plus, Users, X } from 'lucide-react'
import { useAuth } from '../../context/AuthContext'

export default function OrganizationsPage() {
  const { effectiveRole, switchOrganization, refreshOrganizations } = useAuth()
  const [orgs, setOrgs] = React.useState<any[]>([]), [selected, setSelected] = React.useState<any>(null), [members, setMembers] = React.useState<any[]>([])
  const [loading, setLoading] = React.useState(true), [showCreate, setShowCreate] = React.useState(false), [error, setError] = React.useState('')
  const [form, setForm] = React.useState({ name: '', organization_type: 'INDUSTRY', slug: '' })
  const [memberForm, setMemberForm] = React.useState({ user_identifier: '', role: 'INDUSTRY_MEMBER_RECRUITER' })
  const isAdmin = ['INDUSTRY_ADMIN', 'INSTITUTION_ADMIN', 'company', 'institution'].includes(String(effectiveRole))
  const load = React.useCallback(() => { setLoading(true); organizationApi.list().then(r => setOrgs(r.data || [])).catch(() => setError('Unable to load organizations')).finally(() => setLoading(false)) }, [])
  React.useEffect(() => { load() }, [load])
  const select = (org: any) => { switchOrganization(org.id); setSelected(org); organizationApi.members(org.id).then(r => setMembers(r.data || [])).catch(() => setError('Unable to load members')) }
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { const r = await organizationApi.create(form); setShowCreate(false); await refreshOrganizations(); switchOrganization(r.data.id); load() } catch (e: any) { setError(e?.response?.data?.detail || 'Unable to create organization') } }
  const addMember = async (e: React.FormEvent) => { e.preventDefault(); setError(''); try { await organizationApi.addMember(selected.id, memberForm); setMemberForm({ user_identifier: '', role: 'INDUSTRY_MEMBER_RECRUITER' }); select(selected) } catch (e: any) { setError(e?.response?.data?.detail || 'Unable to add member') } }
  return <div className="space-y-6"><div className="flex justify-between items-center"><h1 className="text-2xl font-bold">Organizations</h1>{isAdmin && <button onClick={() => setShowCreate(true)} className="btn-primary flex gap-2"><Plus size={16}/> New organization</button>}</div>{error && <div className="rounded-lg bg-red-50 text-red-700 px-4 py-3">{error}</div>}{showCreate && <form onSubmit={create} className="card space-y-3"><input required placeholder="Organization name" className="input" value={form.name} onChange={e => setForm({...form,name:e.target.value})}/><input required placeholder="Slug" className="input" value={form.slug} onChange={e => setForm({...form,slug:e.target.value})}/><select className="input" value={form.organization_type} onChange={e => setForm({...form,organization_type:e.target.value})}><option>INDUSTRY</option><option>INSTITUTION</option></select><button className="btn-primary">Create</button></form>}{loading ? <div>Loading organizations...</div> : <div className="grid gap-4 md:grid-cols-2">{orgs.map(o => <button key={o.id} onClick={() => select(o)} className="card text-left"><Building2 className="text-blue-600"/><h2 className="font-semibold">{o.name}</h2></button>)}</div>}{selected && <section className="card"><h2 className="font-semibold flex gap-2 mb-4"><Users size={18}/> {selected.name} members</h2>{isAdmin && <form onSubmit={addMember} className="grid md:grid-cols-[1fr_1fr_auto] gap-2 mb-4"><input required className="input" placeholder="Email or username" value={memberForm.user_identifier} onChange={e => setMemberForm({...memberForm,user_identifier:e.target.value})}/><select className="input" value={memberForm.role} onChange={e => setMemberForm({...memberForm,role:e.target.value})}><option>INDUSTRY_MEMBER_RECRUITER</option><option>INDUSTRY_ADMIN</option><option>STUDENT</option><option>FACULTY</option><option>MENTOR_TRAINER</option></select><button className="btn-primary">Add member</button></form>}{members.map(m => <div className="py-2" key={m.id}>{m.user_id} <span className="badge">{m.role}</span></div>)}</section>}</div>
}
