import React, { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { Eye, EyeOff } from 'lucide-react'
import { useAuth } from '../../context/AuthContext'

export default function LoginPage() {
  const { login } = useAuth(); const navigate = useNavigate()
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [showPassword, setShowPassword] = useState(false)
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); setLoading(true); try { await login(email, password); navigate('/student/learning') } catch { setError('Invalid email or password.') } finally { setLoading(false) } }
  return <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100"><div className="card w-full max-w-md"><div className="text-center mb-8"><h1 className="text-3xl font-bold text-blue-700">SkillBridge AI</h1><p className="text-gray-500 mt-2">Assess. Upskill. Connect. Get Hired. Grow.</p></div><form onSubmit={handleSubmit} className="space-y-4"><div><label htmlFor="login-email" className="block text-sm font-medium text-gray-700 mb-1">Email</label><input id="login-email" className="input" type="email" value={email} onChange={e => setEmail(e.target.value)} required placeholder="student.test@gmail.com" /></div><div><label htmlFor="login-password" className="block text-sm font-medium text-gray-700 mb-1">Password</label><div className="relative"><input id="login-password" className="input pr-10" type={showPassword ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} required placeholder="Password" /><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword(v => !v)} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500">{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></div>{error && <p className="text-red-600 text-sm">{error}</p>}<button type="submit" className="btn-primary w-full" disabled={loading}>{loading ? 'Signing in...' : 'Sign In'}</button></form><p className="text-center text-sm text-gray-500 mt-4">Don't have an account? <Link to="/register" className="text-blue-600 hover:underline">Register</Link></p><div className="mt-6 p-3 bg-gray-50 rounded-lg text-xs text-gray-500"><p className="font-medium mb-1">Test accounts (copy email and password):</p><p>Student: student.test@gmail.com / student@123</p><p>Admin: admin.test@example.com / admin@123</p><p>Industry admin: industry.admin.test@example.com / industry@123</p><p>Recruiter: recruiter.test@example.com / recruiter@123</p><p>Institution admin: institution.admin.test@example.com / institution@123</p><p>Faculty: faculty.test@example.com / faculty@123</p><p>Mentor: mentor.test@example.com / mentor@123</p></div></div></div>
}
