import uuid
from datetime import date
from sqlalchemy import *
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.db.base import Base
class StudentProfile(Base):
    __tablename__='student_profiles'; __table_args__=(CheckConstraint('graduation_year BETWEEN 1980 AND 2100'), CheckConstraint('cgpa BETWEEN 0 AND 10'))
    user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),primary_key=True)
    first_name: Mapped[str|None]=mapped_column(String(100)); last_name: Mapped[str|None]=mapped_column(String(100)); phone: Mapped[str|None]=mapped_column(String(50)); summary: Mapped[str|None]=mapped_column(Text); department: Mapped[str|None]=mapped_column(String(150)); degree: Mapped[str|None]=mapped_column(String(150)); institution_name: Mapped[str|None]=mapped_column(String(200)); graduation_year: Mapped[int|None]=mapped_column(Integer); cgpa: Mapped[float|None]=mapped_column(Numeric(4,2)); city: Mapped[str|None]=mapped_column(String(100)); state: Mapped[str|None]=mapped_column(String(100)); linkedin_url: Mapped[str|None]=mapped_column(String(500)); github_url: Mapped[str|None]=mapped_column(String(500)); portfolio_url: Mapped[str|None]=mapped_column(String(500)); resume_file_url: Mapped[str|None]=mapped_column(String(500)); created_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
    user=relationship('User',back_populates='profile')
class StudentSkill(Base):
    __tablename__='student_skills'; __table_args__=(UniqueConstraint('student_id','skill_id'),CheckConstraint("proficiency_level IN ('BEGINNER','INTERMEDIATE','ADVANCED','EXPERT')"),CheckConstraint("source IN ('SELF','ASSESSMENT','CERTIFICATION','TRAINING','INDUSTRY')"),CheckConstraint('score BETWEEN 0 AND 100'))
    id: Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); student_id: Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); skill_id: Mapped[int]=mapped_column(ForeignKey('skills.id')); proficiency_level: Mapped[str]=mapped_column(String(20),default='BEGINNER'); score: Mapped[int|None]=mapped_column(Integer); source: Mapped[str]=mapped_column(String(20),default='SELF'); created_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); skill=relationship('Skill')
class StudentProject(Base):
    __tablename__='student_projects'; id: Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); student_id: Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); title: Mapped[str]=mapped_column(String(200)); description: Mapped[str|None]=mapped_column(Text); technologies: Mapped[list]=mapped_column(JSON,default=list); project_url: Mapped[str|None]=mapped_column(String(500)); start_date: Mapped[date|None]=mapped_column(Date); end_date: Mapped[date|None]=mapped_column(Date); status: Mapped[str]=mapped_column(String(20),default='IN_PROGRESS'); created_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class StudentCertification(Base):
    __tablename__='student_certifications'; id: Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); student_id: Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); name: Mapped[str]=mapped_column(String(200)); issuer: Mapped[str|None]=mapped_column(String(200)); issue_date: Mapped[date|None]=mapped_column(Date); expiry_date: Mapped[date|None]=mapped_column(Date); credential_url: Mapped[str|None]=mapped_column(String(500)); created_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class StudentAchievement(Base):
    __tablename__='student_achievements'; id: Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); student_id: Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); title: Mapped[str]=mapped_column(String(200)); description: Mapped[str|None]=mapped_column(Text); achievement_date: Mapped[date|None]=mapped_column(Date); created_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class StudentInternship(Base):
    __tablename__='student_internships'; id: Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); student_id: Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); company_name: Mapped[str]=mapped_column(String(200)); role: Mapped[str]=mapped_column(String(200)); description: Mapped[str|None]=mapped_column(Text); start_date: Mapped[date|None]=mapped_column(Date); end_date: Mapped[date|None]=mapped_column(Date); status: Mapped[str]=mapped_column(String(20),default='ONGOING'); created_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class StudentPreferredRole(Base):
    __tablename__='student_preferred_roles'; __table_args__=(UniqueConstraint('student_id','career_role_id'),); id: Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); student_id: Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); career_role_id: Mapped[int]=mapped_column(ForeignKey('career_roles.id')); is_primary: Mapped[bool]=mapped_column(Boolean,default=False); created_at: Mapped[DateTime]=mapped_column(DateTime(timezone=True),server_default=func.now()); career_role=relationship('CareerRole')
